M48
; DRILL file KiCad 10.0.6-10.0.6~ubuntu24.04.1 date 2026-09-26T12:21:50
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-26T12:21:50-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6-10.0.6~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X77.11Y139.6
X82.89Y139.6
T2
X41.6Y118.0
X48.4Y118.0
T3
X4.0Y141.0
X4.0Y4.0
X80.0Y106.5
X156.0Y141.0
X156.0Y4.0
M30
