M48
; DRILL file KiCad 10.0.6-10.0.6~ubuntu24.04.1 date 2026-09-23T08:41:50
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-23T08:41:50-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6-10.0.6~ubuntu24.04.1
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C2.000
%
G90
G05
T1
X10.865Y-10.0
X10.865Y-12.5
T2
X5.815Y-4.95
X5.815Y-15.05
M30
